name: energy-publication
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # Core data science
  - numpy=1.21.6
  - pandas=1.5.3
  - scipy=1.9.3
  - scikit-learn=1.1.3

  # Deep learning with CUDA support
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - cudatoolkit=11.7

  # Machine learning
  - xgboost=1.7.4
  - imbalanced-learn=0.9.1

  # Visualization
  - matplotlib=3.6.3
  - seaborn=0.12.2
  - plotly=5.15.0

  # Configuration and utilities
  - pyyaml=6.0
  - loguru=0.6.0
  - joblib=1.2.0
  - tqdm=4.64.1

  # Hyperparameter optimization
  - optuna=3.1.0

  # Jupyter and development
  - jupyter=1.0.0
  - ipykernel=6.19.2
  - notebook=6.5.2

  # Testing
  - pytest=7.2.1
  - pytest-cov=4.0.0

  # Code quality
  - black=22.12.0
  - flake8=6.0.0
  - isort=5.12.0

  # Additional ML libraries
  - lightgbm=3.3.5
  - catboost=1.1.1

  # Pip dependencies (for packages not available in conda)
  - pip
  - pip:
    - transformers==4.21.3
    - pytorch-lightning==1.8.5
    - wandb==0.13.10
    - tensorboard==2.11.2
    - great-expectations==0.15.50
    - mlflow==2.1.1
    - hydra-core==1.2.0
    - omegaconf==2.2.3
    - rich==13.0.1
    - typer==0.7.0