name: heat-pump-stress-detection
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9

  # Core data science
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0

  # Machine learning
  - xgboost>=1.5.0
  - imbalanced-learn>=0.8.0

  # Visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # Configuration and utilities
  - pyyaml>=6.0
  - loguru>=0.6.0
  - joblib>=1.1.0

  # Hyperparameter optimization
  - optuna>=3.0.0

  # Jupyter and development
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - notebook>=6.4.0

  # Testing
  - pytest>=6.0.0
  - pytest-cov>=3.0.0

  # Code quality
  - black>=22.0.0
  - flake8>=4.0.0
  - isort>=5.0.0

  # Pip dependencies (for packages not available in conda)
  - pip
  - pip:
    - great-expectations>=0.15.0